<?xml version="1.0" encoding="UTF-8"?><testrun name="HashMapTest (1)" project="JavaConcurrencyTest" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="concurrent.util.classes.tests.HashMapTest" time="0.0">
    <testcase name="test" classname="concurrent.util.classes.tests.HashMapTest" time="0.0">
      <error>java.lang.Error: java.lang.SecurityException: Unsafe
	at concurrent.util.classes.ConcurrentHashMap.&lt;clinit&gt;(ConcurrentHashMap.java:6340)
	at concurrent.util.classes.tests.HashMapTest.&lt;clinit&gt;(HashMapTest.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at edu.tamu.aser.exploration.JUnit4MCRRunner.access$2(JUnit4MCRRunner.java:1)
	at edu.tamu.aser.exploration.JUnit4MCRRunner$1.run(JUnit4MCRRunner.java:75)
Caused by: java.lang.SecurityException: Unsafe
	at sun.misc.Unsafe.getUnsafe(Unsafe.java:90)
	at concurrent.util.classes.ConcurrentHashMap.&lt;clinit&gt;(ConcurrentHashMap.java:6320)
	... 12 more

</error>
    </testcase>
  </testsuite>
</testrun>
